name: Workflow con expresiones

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16, 18]  # Expresión de matriz

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}  # Expresión de matriz

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
        if: ${{ contains(github.event.head_commit.message, 'test') }}  # Expresión de condición con función

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to production
        run: echo "Deploying..."
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}  # Condicional