name: Recordatorio del 10 de noviembre

on:
  # Triggers del workflow
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Trigger programado para el 10 de noviembre a las 09:00 UTC
  schedule:
    - cron: '0 9 10 11 *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Send reminder
      run: echo "¡Recordatorio! Hoy es 10 de noviembre."